[theme]
base="dark"
backgroundColor="#2c3e50"          # slate blue-grey (dark but not black)
secondaryBackgroundColor="#34495e" # slightly lighter slate for contrast
textColor="#ecf0f1"                # soft white for readability
primaryColor="#4d908e"             # teal highlight
font="sans serif"
